### PR TITLE
ACTION_GET_CONTENT and Image converters

### PR DESCRIPTION
**Pull request by saadfarooq**
Refactored to use the recommended ACTION_GET_CONTENT and added coverters so images can be used in desired format

### CODE REVIEW

**Comment by saadfarooq** [comment]
Also did some cleanup around the .gitignore.

**Comment by saadfarooq** [comment]
Can we get a new release soon? If it going to take a while let me know and I'll just do a local maven deploy in the mean time. Looking to start using this in our app soon.

**Comment by Frederikos** [comment]
It's already updated in com.mlsdev.rximagepicker:library:1.1.2

**Comment by saadfarooq** [comment]
Awesome. Thanks.

**Pull request merged**
